from backend.etl.load_utils import batch_upsert

# going to only upload to games table first.
# later, need to figure out how to update to teams table. create new clean.py for games? or second function / parameters?

# for teams, need name, abbreviation, conference, division
# id is generated by supabase

def load_teams(raw_games: list[dict]):
    teams = {}
    try:
        for game in raw_games:
            home = game["home_team"]
            away = game["visitor_team"]

            teams[home["id"]] = {
                "id":home["id"],
                "name":home["name"],
                "abbreviation":home["abbreviation"],
                "conference":home["conference"],
                "division":home["division"]
            }

            teams[away["id"]] = {
                "id": away["id"],
                "name": away["name"],
                "abbreviation": away["abbreviation"],
                "conference": away["conference"],
                "division": away["division"]
            }

    except Exception as e:
        print(f"Error data parsing load_teams: {e}")
        return False
    
    teams_rows = list(teams.values())

    try:
        batch_upsert("teams",teams_rows,"id",100)
        print("Batch upserted teams to supabase sucessfully")
        return True
    except Exception as e:
        print(f"Error with batch upsert in load_teams: {e}")
        return False
            
            
def load_games(cleaned_games: list[dict]):
    cleaned_games = [g for g in cleaned_games if g is not None]
    print("Number of cleaned games: ", len(cleaned_games))

    try:
        batch_upsert("games",cleaned_games,"external_game_id",100) 
        print("Batch upserted games to supabase successfully.")
        return True
    except Exception as e:
        print(f"Error with batch upsert in load_games: {e}")
        return False
 
